version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: estateflow-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./server
    container_name: estateflow-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/estateflow
      - JWT_SECRET=estate_master_secret_2026
    depends_on:
      - mongodb

  frontend:
    build: ./client
    container_name: estateflow-frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mongo_data:
